using System.Collections.Generic;

namespace BingoRoulette
{
	public static class GlobalValue
	{
		// Google Spread Sheet
		public static readonly string DataInstanceName = "Name";
		public static readonly string IgnorePrefix = "#";

		// File Path
		public static readonly string SOCreatePath = "Assets/Resources/SO/AutoGenerated";
		public static readonly string ScriptPath = "Assets/Scripts/AutoGenerated";

		// Addressable
		// public static readonly string SOLabel = "ScriptableObject";
		
		// Resources
		public static readonly string SOResourcePath = "SO/AutoGenerated";

		// Roulette
		public static readonly int SlotRowCount = 5; // 룰렛 세로 수
		public static readonly int SlotColCount = 5; // 룰렛 가로 수

		// Probability
		public static readonly int ProbabilityMaxCount = 100000; // 확률 계산 기준 정수
		
		// Steam Achievement
		public static readonly Dictionary<int, EAchievement> PointAchievements =
			new Dictionary<int, EAchievement>
			{
				{ 100,  EAchievement.GET_100_POINTS },
				{ 200,  EAchievement.GET_200_POINTS },
				{ 300,  EAchievement.GET_300_POINTS },
				{ 400,  EAchievement.GET_400_POINTS },
				{ 500,  EAchievement.GET_500_POINTS },
				{ 600,  EAchievement.GET_600_POINTS },
				{ 700,  EAchievement.GET_700_POINTS },
				{ 800,  EAchievement.GET_800_POINTS },
				{ 900,  EAchievement.GET_900_POINTS },
				{ 1000, EAchievement.GET_1000_POINTS },
			};
	}
}
